export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-OmniRoute-Cache",
  cacheHit: "X-OmniRoute-Cache-Hit",
  cacheLatency: "X-OmniRoute-Cache-Latency",
  cacheSimilarity: "X-OmniRoute-Cache-Similarity",
  savingsTokens: "X-OmniRoute-Savings-Tokens",
  compression: "X-OmniRoute-Compression",
  costSaved: "X-OmniRoute-Cost-Saved",
  decision: "X-OmniRoute-Decision",
  accountFallbacks: "X-OmniRoute-Account-Fallbacks",
  accountFallbackReasons: "X-OmniRoute-Account-Fallback-Reasons",
  selectedConnectionPlan: "X-OmniRoute-Selected-Connection-Plan",
  sameAccountRetries: "X-OmniRoute-Same-Account-Retries",
  routingWaitMs: "X-OmniRoute-Routing-Wait-Ms",
  fallbackAttempts: "X-OmniRoute-Fallback-Attempts",
  latencyMs: "X-OmniRoute-Latency-Ms",
  model: "X-OmniRoute-Model",
  progress: "X-OmniRoute-Progress",
  provider: "X-OmniRoute-Provider",
  requestId: "X-OmniRoute-Request-Id",
  responseCost: "X-OmniRoute-Response-Cost",
  tokensIn: "X-OmniRoute-Tokens-In",
  tokensOut: "X-OmniRoute-Tokens-Out",
  tokensPerSecond: "X-OmniRoute-Tokens-Per-Second",
  version: "X-OmniRoute-Version",
} as const;
